import { letterActivityActionLabels } from '@/lib/letterActivityPresentation';
import type {
    LetterActivityFilterOptions,
    LetterActivityRecord,
} from '@/types';

export const letterActivityPreviewTimezone = 'Asia/Makassar';
export const letterActivityPreviewDate = '2026-08-30';

export const letterActivityPreviewOptions: LetterActivityFilterOptions = {
    actions: Object.entries(letterActivityActionLabels).map(
        ([value, label]) => ({
            value: value as keyof typeof letterActivityActionLabels,
            label,
        }),
    ),
    sources: [
        { value: 'public', label: 'Portal publik' },
        { value: 'internal', label: 'Back-office' },
    ],
    actors: [
        { value: '11', label: 'Aisyah Rahman' },
        { value: '12', label: 'Fahri Hidayat' },
        { value: '13', label: 'Nur Aulia' },
        { value: '501', label: 'Rizal Pratama' },
    ],
};

export const letterActivityPreviewRecords: LetterActivityRecord[] = [
    {
        id: 108,
        action: 'DOCUMENT_VERSION_CREATED',
        actor: {
            kind: 'internal',
            id: 13,
            name: 'Nur Aulia',
            position: 'Kepala Bagian Umum',
            unit: 'Bagian Umum',
        },
        target: {
            public_id: 'SUB-2026-000184',
            agenda_number: 'AGD/2026/08/0042',
            subject: 'Permohonan audiensi pengembangan UMKM pesisir',
            sender: 'Forum UMKM Kota',
            source: 'ONLINE',
        },
        before: null,
        after: {
            versi_dokumen: 1,
            status_integritas: 'Terverifikasi',
        },
        document: {
            version_number: 1,
            sha256: '8f0d39b320ee3bb5eb64c225f0deabcb18e39b2c7dd6f76a4f61e307ac701f89',
        },
        request_id: 'req-01J6A50Z0YJP0M14N1R94V7TMR',
        ip_address: '10.14.2.18',
        user_agent: 'Chrome 128 · Windows',
        occurred_at: '2026-08-30T06:18:42Z',
    },
    {
        id: 107,
        action: 'LETTER_REGISTERED',
        actor: {
            kind: 'internal',
            id: 13,
            name: 'Nur Aulia',
            position: 'Kepala Bagian Umum',
            unit: 'Bagian Umum',
        },
        target: {
            public_id: 'SUB-2026-000184',
            agenda_number: 'AGD/2026/08/0042',
            subject: 'Permohonan audiensi pengembangan UMKM pesisir',
            sender: 'Forum UMKM Kota',
            source: 'ONLINE',
        },
        before: { status: 'Siap ditinjau Kabag' },
        after: {
            status: 'Terdaftar',
            nomor_agenda: 'AGD/2026/08/0042',
        },
        document: null,
        request_id: 'req-01J6A50Z0YJP0M14N1R94V7TMR',
        ip_address: '10.14.2.18',
        user_agent: 'Chrome 128 · Windows',
        occurred_at: '2026-08-30T06:18:41Z',
    },
    {
        id: 106,
        action: 'SUBMISSION_READY_FOR_APPROVAL',
        actor: {
            kind: 'internal',
            id: 12,
            name: 'Fahri Hidayat',
            position: 'Petugas Administrasi Surat',
            unit: 'Bagian Umum',
        },
        target: {
            public_id: 'SUB-2026-000191',
            agenda_number: null,
            subject: 'Undangan koordinasi penanggulangan banjir',
            sender: 'BPBD Provinsi',
            source: 'ONLINE',
        },
        before: { status: 'Dalam pemeriksaan' },
        after: { status: 'Siap ditinjau Kabag' },
        document: null,
        request_id: 'req-01J6A4J84ZR3P8AQ2RRT49P2VQ',
        ip_address: '10.14.2.31',
        user_agent: 'Firefox 129 · Ubuntu',
        occurred_at: '2026-08-30T05:42:08Z',
    },
    {
        id: 105,
        action: 'SUBMISSION_RETURNED_TO_STAFF',
        actor: {
            kind: 'internal',
            id: 13,
            name: 'Nur Aulia',
            position: 'Kepala Bagian Umum',
            unit: 'Bagian Umum',
        },
        target: {
            public_id: 'SUB-2026-000179',
            agenda_number: null,
            subject: 'Permohonan penggunaan aula kantor wali kota',
            sender: 'Komunitas Pemuda Kreatif',
            source: 'ONLINE',
        },
        before: { status: 'Siap ditinjau Kabag' },
        after: {
            status: 'Perlu diperiksa ulang',
            catatan: 'Periksa kembali kesesuaian tanggal kegiatan.',
        },
        document: null,
        request_id: 'req-01J6A3V19WT84RAYMJ7MP11B58',
        ip_address: '10.14.2.18',
        user_agent: 'Chrome 128 · Windows',
        occurred_at: '2026-08-30T04:55:16Z',
    },
    {
        id: 104,
        action: 'SUBMISSION_REVISION_REQUESTED',
        actor: {
            kind: 'internal',
            id: 11,
            name: 'Aisyah Rahman',
            position: 'Petugas Administrasi Surat',
            unit: 'Bagian Umum',
        },
        target: {
            public_id: 'SUB-2026-000193',
            agenda_number: null,
            subject: 'Permohonan rekomendasi kegiatan kebudayaan',
            sender: 'Sanggar Seni Bahari',
            source: 'ONLINE',
        },
        before: { status: 'Dalam pemeriksaan' },
        after: {
            status: 'Menunggu perbaikan pemohon',
            catatan: 'Lampiran jadwal kegiatan belum disertakan.',
        },
        document: null,
        request_id: 'req-01J6A31JC8ZQSWTPDXXA0Z6PKF',
        ip_address: '10.14.2.27',
        user_agent: 'Edge 128 · Windows',
        occurred_at: '2026-08-30T03:36:27Z',
    },
    {
        id: 103,
        action: 'SUBMISSION_RESUBMITTED',
        actor: {
            kind: 'public',
            id: 501,
            name: 'Rizal Pratama',
            position: null,
            unit: null,
        },
        target: {
            public_id: 'SUB-2026-000172',
            agenda_number: null,
            subject: 'Permohonan data statistik daerah',
            sender: 'Lembaga Riset Nusantara',
            source: 'ONLINE',
        },
        before: { status: 'Menunggu perbaikan pemohon' },
        after: { status: 'Diajukan kembali' },
        document: null,
        request_id: 'req-01J6A2A2MPK0ZWWQFET84R12DS',
        ip_address: '180.251.xxx.xxx',
        user_agent: 'Safari 17 · macOS',
        occurred_at: '2026-08-30T02:48:11Z',
    },
    {
        id: 102,
        action: 'SUBMISSION_REJECTED',
        actor: {
            kind: 'internal',
            id: 13,
            name: 'Nur Aulia',
            position: 'Kepala Bagian Umum',
            unit: 'Bagian Umum',
        },
        target: {
            public_id: 'SUB-2026-000167',
            agenda_number: null,
            subject: 'Penawaran kerja sama pengadaan perangkat',
            sender: 'PT Solusi Digital Timur',
            source: 'ONLINE',
        },
        before: { status: 'Siap ditinjau Kabag' },
        after: {
            status: 'Ditolak',
            alasan: 'Tidak sesuai kanal dan kewenangan penerimaan surat.',
        },
        document: null,
        request_id: 'req-01J6A1M09Y7F3TY0HA9KCQEHGJ',
        ip_address: '10.14.2.18',
        user_agent: 'Chrome 128 · Windows',
        occurred_at: '2026-08-30T01:52:06Z',
    },
    {
        id: 101,
        action: 'SUBMISSION_SUBMITTED',
        actor: {
            kind: 'public',
            id: 501,
            name: 'Rizal Pratama',
            position: null,
            unit: null,
        },
        target: {
            public_id: 'SUB-2026-000196',
            agenda_number: null,
            subject: 'Permohonan kunjungan edukasi ke kantor wali kota',
            sender: 'SMA Negeri 4',
            source: 'ONLINE',
        },
        before: null,
        after: { status: 'Diajukan' },
        document: null,
        request_id: 'req-01J6A0WZR2JXV2C1R4VREX1WEG',
        ip_address: '114.122.xxx.xxx',
        user_agent: 'Chrome Mobile 128 · Android',
        occurred_at: '2026-08-30T00:34:49Z',
    },
];
