<?php

namespace App\Enums;

enum AuditAction: string
{
    case InternalAccountProvisioned = 'INTERNAL_ACCOUNT_PROVISIONED';
    case RoleChanged = 'ROLE_CHANGED';
    case PermissionChanged = 'PERMISSION_CHANGED';
    case SubmissionCreated = 'SUBMISSION_CREATED';
    case SubmissionUpdated = 'SUBMISSION_UPDATED';
    case SubmissionDocumentReplaced = 'SUBMISSION_DOCUMENT_REPLACED';
    case SubmissionSubmitted = 'SUBMISSION_SUBMITTED';
    case SubmissionResubmitted = 'SUBMISSION_RESUBMITTED';
    case SubmissionRevisionRequested = 'SUBMISSION_REVISION_REQUESTED';
    case SubmissionReadyForApproval = 'SUBMISSION_READY_FOR_APPROVAL';
    case SubmissionReturnedToStaff = 'SUBMISSION_RETURNED_TO_STAFF';
    case SubmissionRejected = 'SUBMISSION_REJECTED';
    case SubmissionDraftDeleted = 'SUBMISSION_DRAFT_DELETED';
    case ManualSubmissionCreated = 'MANUAL_SUBMISSION_CREATED';
    case LetterRegistered = 'LETTER_REGISTERED';
    case LetterRouted = 'LETTER_ROUTED';
    case DispositionCreated = 'DISPOSITION_CREATED';
    case DispositionStarted = 'DISPOSITION_STARTED';
    case FollowUpAdded = 'FOLLOW_UP_ADDED';
    case DispositionCompleted = 'DISPOSITION_COMPLETED';
    case LetterCompleted = 'LETTER_COMPLETED';
    case LetterResponseDossierOpened = 'LETTER_RESPONSE_DOSSIER_OPENED';
    case LetterResponseDocumentVersionCreated = 'LETTER_RESPONSE_DOCUMENT_VERSION_CREATED';
    case LetterResponseDocumentReturned = 'LETTER_RESPONSE_DOCUMENT_RETURNED';
    case LetterResponseMandateAuthorized = 'LETTER_RESPONSE_MANDATE_AUTHORIZED';
    case LetterResponseDossierFinalized = 'LETTER_RESPONSE_DOSSIER_FINALIZED';
    case OutgoingLetterNumberAssigned = 'OUTGOING_LETTER_NUMBER_ASSIGNED';
    case OutgoingLetterDocumentVersionCreated = 'OUTGOING_LETTER_DOCUMENT_VERSION_CREATED';
    case OutgoingLetterDocumentReturned = 'OUTGOING_LETTER_DOCUMENT_RETURNED';
    case OutgoingLetterAdminVerified = 'OUTGOING_LETTER_ADMIN_VERIFIED';
    case OutgoingLetterDelivered = 'OUTGOING_LETTER_DELIVERED';
    case OutgoingLetterMandateWithdrawn = 'OUTGOING_LETTER_MANDATE_WITHDRAWN';
    case LetterResponseDossierFulfilled = 'LETTER_RESPONSE_DOSSIER_FULFILLED';
    case InstructionLabelCreated = 'INSTRUCTION_LABEL_CREATED';
    case InstructionLabelUpdated = 'INSTRUCTION_LABEL_UPDATED';
    case InstructionLabelStatusChanged = 'INSTRUCTION_LABEL_STATUS_CHANGED';
    case DocumentVersionCreated = 'DOCUMENT_VERSION_CREATED';
    case PositionAssigned = 'POSITION_ASSIGNED';
    case PositionHolderReplaced = 'POSITION_HOLDER_REPLACED';
    case PositionAssignmentEnded = 'POSITION_ASSIGNMENT_ENDED';
    case PositionLevelCatalogSynchronized = 'POSITION_LEVEL_CATALOG_SYNCHRONIZED';
    case OrganizationalUnitCreated = 'ORGANIZATIONAL_UNIT_CREATED';
    case OrganizationalUnitUpdated = 'ORGANIZATIONAL_UNIT_UPDATED';
    case OrganizationalUnitStatusChanged = 'ORGANIZATIONAL_UNIT_STATUS_CHANGED';
    case PositionCreated = 'POSITION_CREATED';
    case PositionUpdated = 'POSITION_UPDATED';
    case PositionStatusChanged = 'POSITION_STATUS_CHANGED';
    case OutgoingTemplateVersionCreated = 'OUTGOING_TEMPLATE_VERSION_CREATED';
    case OutgoingTemplateStatusChanged = 'OUTGOING_TEMPLATE_STATUS_CHANGED';
    case StandaloneOutgoingDraftCreated = 'STANDALONE_OUTGOING_DRAFT_CREATED';
    case StandaloneOutgoingDraftUpdated = 'STANDALONE_OUTGOING_DRAFT_UPDATED';
    case StandaloneOutgoingDocumentVersionCreated = 'STANDALONE_OUTGOING_DOCUMENT_VERSION_CREATED';
    case StandaloneOutgoingSubmitted = 'STANDALONE_OUTGOING_SUBMITTED';
    case StandaloneOutgoingReviewed = 'STANDALONE_OUTGOING_REVIEWED';
    case StandaloneOutgoingNumberAssigned = 'STANDALONE_OUTGOING_NUMBER_ASSIGNED';
    case StandaloneOutgoingSubmittedToSekda = 'STANDALONE_OUTGOING_SUBMITTED_TO_SEKDA';
    case StandaloneOutgoingQrApproved = 'STANDALONE_OUTGOING_QR_APPROVED';
    case StandaloneOutgoingManualSignatureSelected = 'STANDALONE_OUTGOING_MANUAL_SIGNATURE_SELECTED';
    case StandaloneOutgoingManualScanUploaded = 'STANDALONE_OUTGOING_MANUAL_SCAN_UPLOADED';
    case StandaloneOutgoingManualScanReviewed = 'STANDALONE_OUTGOING_MANUAL_SCAN_REVIEWED';
    case StandaloneOutgoingReturnedBySekda = 'STANDALONE_OUTGOING_RETURNED_BY_SEKDA';
    case StandaloneOutgoingDelivered = 'STANDALONE_OUTGOING_DELIVERED';
    case StandaloneOutgoingEmailLinkIssued = 'STANDALONE_OUTGOING_EMAIL_LINK_ISSUED';
    case StandaloneOutgoingEmailLinkRevoked = 'STANDALONE_OUTGOING_EMAIL_LINK_REVOKED';
    case StandaloneOutgoingCorrectionDraftCreated = 'STANDALONE_OUTGOING_CORRECTION_DRAFT_CREATED';
    case ExpertConsultationRequested = 'EXPERT_CONSULTATION_REQUESTED';
    case ExpertConsultationReported = 'EXPERT_CONSULTATION_REPORTED';
    case ExpertConsultationCancelled = 'EXPERT_CONSULTATION_CANCELLED';
}
